import Head from "next/head";
import Image from "next/image";
import { useUser, SignInButton } from "@clerk/nextjs";

import { api } from "~/utils/api";

export default function Home() {
  const user = useUser();
  const { data, isLoading } = api.post.getAll.useQuery();

  if (isLoading) return <div>Loading...</div>;

  if (!data) return <div>Something went wrong</div>;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen justify-center">
        <div className="w-full border-x border-slate-400 md:max-w-2xl">
          <div className="border-b border-slate-400 p-4 ">
            <div className="flex justify-center">
              {user.isSignedIn ? <CreatePostWizard /> : <SignInButton />}
            </div>
          </div>
          <div className="flex flex-col">
            {[...data, ...data].map(({ post, author }) => (
              <div key={post.id} className="flex flex-col w-full border-b border-slate-400 p-8">
                <div className="font-semibold">{author?.username}</div>
                <div>{post.content}</div>
              </div>
            ))}
          </div>
        </div>
      </main>
    </>
  );
}

const CreatePostWizard = () => {
  const { user } = useUser();

  if (!user) return null;

  return (
    <div className="flex w-full gap-3">
      <Image
        src={user.imageUrl}
        alt="Profile image"
        className="h-10 w-10 rounded-full"
        width={48}
        height={48}
      />
      <input
        placeholder="Type some emojis..."
        className="grow bg-transparent outline-none"
      />
    </div>
  );
};
