import Head from "next/head";
import Image from "next/image";
import { useUser, SignInButton } from "@clerk/nextjs";

import dayjs from 'dayjs';
import relativeTime from "dayjs/plugin/relativeTime";

import { RouterOutputs, api } from "~/utils/api";

dayjs.extend(relativeTime);

export default function Home() {
  const user = useUser();
  const { data, isLoading } = api.post.getAll.useQuery();

  if (isLoading) return <div>Loading...</div>;

  if (!data) return <div>Something went wrong</div>;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen justify-center">
        <div className="w-full border-x border-slate-700 md:max-w-2xl">
          <div className="border-b border-slate-700 p-4 ">
            <div className="flex justify-center">
              {user.isSignedIn ? <CreatePostWizard /> : <SignInButton />}
            </div>
          </div>
          <div className="flex flex-col">
            {[...data, ...data].map((fullPost) => (
              <PostView key={fullPost.post.id} {...fullPost} />
            ))}
          </div>
        </div>
      </main>
    </>
  );
}

const CreatePostWizard = () => {
  const { user } = useUser();

  if (!user) return null;

  return (
    <div className="flex w-full gap-3">
      <Image
        src={user.imageUrl}
        alt="Profile image"
        className="h-10 w-10 rounded-full"
        width={48}
        height={48}
      />
      <input
        placeholder="Type some emojis..."
        className="grow bg-transparent outline-none"
      />
    </div>
  );
};

type PostWithUser = RouterOutputs["post"]["getAll"][number];
const PostView = (props: PostWithUser) => {
  const { post, author } = props;

  return (
    <div
      key={post.id}
      className="flex w-full items-start border-b border-slate-700 p-8 gap-x-3"
    >
      <Image
        src={author.imageUrl}
        alt={`${author.username}}'s profile image`}
        width={36}
        height={36}
        className="h-10 w-10 rounded-full"
      />
      <div className="flex flex-col w-full">
        <div className="flex w-full justify-between items-center">
        <span className="font-medium text-slate-400 hover:text-slate-200">{`@${author.username}`}</span>
        <span className="text-slate-500 text-sm">{dayjs(post.createdAt).fromNow()}</span>
        </div>
        <span>{post.content}</span>
      </div>
    </div>
  );
};
