import Head from "next/head";

export default function SinglePost() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen justify-center">
        <div>
          Single post!
        </div>
      </main>
    </>
  );
}